### PR TITLE
Fix edit variations

### PR DESCRIPTION
**Pull request by shylux**
The check for disabled buttons didn't work (or not anymore).

Also jquery ui is not automatically installed even though we use its `sortable` function. On our installations it got installed ether by hand or by another package.
Should i add an upgrade-step to make sure jquery ui is installed?

@jone

### CODE REVIEW

**Comment by lukasgraf** [comment]
@shylux profile version bump & upgrade step?

**Comment by shylux** [comment]
@lukasgraf fixed

**Comment by lukasgraf** [comment]
:+1:

**Comment by maethu** [comment]
I'm a little bit afraid, running this uprade step, since I habe allready jqueryui installed and configured, does this fix change my configuration?

**Pull request merged**
